### ISSUE TITLE
标记下吧  32  64 绝对路劲 jvm.dll

### ISSUE THREAD

**Issue by marklove5102** [dbyoung720/JavaTest#1]
FDLLHandle := LoadLibraryEx(PChar('C:\Users\freem\.jdks\corretto-1.8.0_252\jre\bin\server\'+FJVMDLLFile),0,LOAD_WITH_ALTERED_SEARCH_PATH);
  //FDLLHandle := LoadLibrary(PChar(FJVMDLLFile));
现在大多数都是 64 了。。然后clone 下来直接32 一直报 dll 不在 path 也设置了。。然后发现32 64问题。。。   自己坑自己。

**Comment by dbyoung720** [comment]
已经更新readme.txt
